// Mapeo de símbolos a los símbolos de Twelve Data API
export const TWELVE_DATA_SYMBOLS: Record<string, string> = {
  // Indices
  'S&P 500': 'SPX',
  'NASDAQ': 'IXIC',
  'DOW': 'DJI',
  'FTSE': 'FTSE',
  'NIKKEI': 'N225',
  'HANG SENG': 'HSI',
  'SHANGHAI': '000001.SS',
  'ASX 200': 'AXJO',
  'SENSEX': 'BSESN',
  'KOSPI': 'KS11',
  'DAX': 'GDAXI',
  'CAC 40': 'FCHI',
  'IBEX': 'IBEX',
  'FTSE MIB': 'FTSEMIB',
  'AEX': 'AEX',
  'MERVAL': 'MERV',
  'IBOVESPA': 'BVSP',
  'IPC': 'MXX',
  'IPSA': 'IPSA',
  'IGBC': 'IGBC',
  
  // Forex
  'USD/EUR': 'EUR/USD',
  'USD/GBP': 'GBP/USD',
  'USD/JPY': 'USD/JPY',
  'EUR/GBP': 'EUR/GBP',
  'USD/CHF': 'USD/CHF',
  'USD/MXN': 'USD/MXN',
  'USD/BRL': 'USD/BRL',
  'USD/CNY': 'USD/CNY',
  'EUR/JPY': 'EUR/JPY',
  'GBP/JPY': 'GBP/JPY',
  'USD/ZAR': 'USD/ZAR',
  'USD/TRY': 'USD/TRY',
  'USD/SGD': 'USD/SGD',
  'EUR/CHF': 'EUR/CHF',
  'AUD/USD': 'AUD/USD',
  
  // Commodities
  'Gold': 'XAU/USD',
  'Crude Oil': 'CL',
  'Silver': 'XAG/USD',
  'Copper': 'HG',
  'Natural Gas': 'NG',
  'Brent': 'BZ',
  'WTI': 'CL',
  'Platinum': 'XPT/USD',
  'Palladium': 'XPD/USD',
  'Aluminum': 'ALI',
  'Wheat': 'ZW',
  'Corn': 'ZC',
  'Soybeans': 'ZS',
  'Coffee': 'KC',
  'Sugar': 'SB',
};

