/**
 * Custom Cloudflare Worker entry point.
 *
 * Re-exports the OpenNext generated fetch handler (which handles all HTTP
 * traffic) and adds a `scheduled` export for cron-triggered auth session
 * cleanup. This is the only way to attach a cron trigger to an OpenNext/CF
 * app — the generated .open-next/worker.js does not expose a scheduled hook.
 *
 * wrangler.jsonc must point `"main"` to the built output of this file, NOT
 * to .open-next/worker.js directly.
 *
 * Build note: This file is bundled by the opennextjs-cloudflare CLI during
 * `npm run deploy`. The `open-next.config.ts` `workerEntrypoint` field
 * (when supported) or a post-build wrangler step can reference it.
 *
 * IMPORTANT: Until @opennextjs/cloudflare exposes a `workerEntrypoint` hook,
 * use the two-step build in package.json:
 *   opennextjs-cloudflare build && wrangler deploy --keep-vars
 *
 * If the OpenNext build overwrites the main entry, set `"main"` in
 * wrangler.jsonc to point to this workers/index.ts and use `wrangler deploy`
 * (which runs esbuild on this file) rather than having OpenNext set main
 * automatically. See wrangler.jsonc comment for the current wiring.
 */

// Re-export the OpenNext fetch handler. The path resolves to the single
// bundle generated by opennextjs-cloudflare at build time.
export { default } from '../.open-next/worker.js';

import { drizzle } from 'drizzle-orm/d1';
import { cleanup } from '../lib/auth/cleanup';

export interface Env {
    DB: D1Database;
    [key: string]: unknown;
}

/**
 * Scheduled trigger handler.
 * Invoked daily by the Cloudflare cron defined in wrangler.jsonc.
 * Deletes expired session and oauth_state rows from D1.
 */
export const scheduled: ExportedHandlerScheduledHandler<Env> = async (_event, env, _ctx) => {
    const db = drizzle(env.DB);
    await cleanup(db, Date.now());
};
