// Merges Okta SSO env bindings into the CloudflareEnv interface generated by
// `wrangler types`. When cloudflare-env.d.ts is regenerated, add DB + these
// secrets there and remove this file to avoid duplicate declarations.
interface CloudflareEnv {
    DB: D1Database;
    OKTA_CLIENT_ID: string;
    OKTA_CLIENT_SECRET: string;
    OKTA_ISSUER: string;
    OKTA_CALLBACK_URL: string;
    OKTA_REDIRECT_URL: string;
    OKTA_POST_LOGOUT_REDIRECT_URI: string;
    OKTA_ALLOWED_EMAILS: string;
    COOKIE_DOMAIN: string;
    SESSION_TTL_DAYS?: string;
    STATE_TTL_SEC?: string;
}
